# Generated by Django 5.2.13 on 2026-05-12 21:33

import questions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=questions.models.avatar_upload_to, verbose_name='Аватар'),
        ),
    ]
